### ISSUE TITLE
More obj files

### ISSUE THREAD

**Issue by ehaupt** [autopawn/3d-ascii-viewer#10]
I found some cool obj files at http://sid.ethz.ch/debian/3d-ascii-viewer-c/ that can be used with 3d-ascii-viewer-c.

**Comment by autopawn** [comment]
Hello! I think that was made by @alexmyczko, and posted in #7.

What is stopping me from adding new models to the repo is #12.

**Comment by autopawn** [comment]
Duplicate of #12
